[package]
name = "rofi-game-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rofi = "0.3.0"
serde = { version = "1.0.144", features = ["derive"] }
toml = "0.5.9"
